### ISSUE TITLE
using  Eurostat NUTS/LAU numbers for references values

### ISSUE THREAD

**Issue by ImreSamu** [osm-without-borders/cosmogony-data-dashboard#6]
Hi!
:heart:    maybe relevant :heart:  

https://ec.europa.eu/eurostat/web/nuts/national-structures-eu 
* `"last update 10/04/2018, based on NUTS 2016 and LAU 2017"` 
* imho: at least the LAU(local-administrative-units) numbers can be used.
  * https://ec.europa.eu/eurostat/web/nuts/local-administrative-units
 * `These LAUs are the building blocks of the NUTS, and comprise the municipalities and communes of the European Union.`
  * `Since 2017, only one level of LAU has been kept.`
  * `Since there are frequent changes to the LAUs, Eurostat publishes an updated list towards the end of each year.`

examples:

### FR	- Q142 - France
* NUTS1 / Z.E.A.T + DOM	 : 14	
* NUTS2 / Régions + DOM	 : 27	
* NUTS3 / Départements + DOM: 101	
* LAU / Communes: 35 462

### LU - Q32 - Luxembourg
* NUTS1: 1	
* NUTS2: 1	
* NUTS3: 1	
* LAU / Communes :	105

### HU - Q28 - Hungary
( `local_knowledge=yes` )
The Hungarian Eurostat numbers looks OK  for references values ; 
but somewhere the  OSM(hu) is not uptodate ->  https://www.ksh.hu/regional_atlas_counties?lang=en 

* NUTS1/ Statisztikai nagyrégiók : 3
  *  osm : ` admin_level=4 and boundary=administrative  in Hungary` 	
* NUTS2/ Tervezési-statisztikai régiók  : 8 	 
  *  osm:   ` admin_level=5 and boundary=administrative  in Hungary` 	(  count= 7 - need update!!  )
* NUTS3 / Megyék + Budapest : 20	
  *  osm:   ` admin_level=6 and boundary=administrative  in Hungary` 
* LAU / Települések :   3 155	
  *  osm:   ` admin_level=8 and boundary=administrative  in Hungary`

**Comment by nlehuby** [comment]
Thanks a lot for that links :+1: 

You are right, the NUTS may provide valuable information about the numbers of administrative zones we should expect in each countries, but I don't think we can use them as is : as they are primarily for statistical purposes and do not necessarily correspond to administrative divisions within the country, some local knowledge is still required.

For instance, for France
* the NUTS1 are not really relevant
* the NUTS2 relate to an old French subdivision
* the NUTS3 and the LAU seem ok :wink: 

If you know these numbers are ok in Hungary, we would gratefully accept some PR :
* in the file that tells us how to extract administrative zones from OSM : https://github.com/osm-without-borders/libpostal/blob/master/resources/boundaries/osm/hu.yaml
* in the file that tells how many zones we should expect for each country : https://github.com/osm-without-borders/cosmogony-data-dashboard/blob/master/reference_stats_values.csv#L176

**Comment by ImreSamu** [comment]
Thanks,  :+1: 

I have created a small fix for Hungary: https://github.com/osm-without-borders/cosmogony-data-dashboard/pull/7

small feedback/comment:   it is hard to find country names because now it is in FR(`Hongrie`) and I am searched for  EN(`Hungary`)
